[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] } # for player stat
tokio = { version = "1.0", features = ["full"] } # for multiplayers
